name: Update Repository List

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 3'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.1

    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements.txt

    - name: Generate repository list
      run: |
        python3 update.py

    - name: Commit and push changes
      uses: actions/github-script@0.10.0
      with:
        script: |
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git add README.md
          git commit -m 'Update repository list'
          git push origin HEAD
